# Dataset
ds_name: weinstock2016
data_csv_path: ./raw_data/weinstock.csv
index_col: -1
observation_interval: 5min

# Columns
column_definition:
  - name: id
    data_type: categorical
    input_type: id
  - name: time
    data_type: date
    input_type: time
  - name: gl
    data_type: real_valued
    input_type: target
  - name: Height
    data_type: real_valued
    input_type: static_input
  - name: Weight
    data_type: real_valued
    input_type: static_input  
  - name: Gender
    data_type: categorical
    input_type: static_input
  - name: Race
    data_type: categorical
    input_type: static_input
  - name: EduLevel
    data_type: categorical
    input_type: static_input
  - name: AnnualInc
    data_type: real_valued
    input_type: static_input
  - name: MaritalStatus
    data_type: categorical
    input_type: static_input
  - name: DaysWkEx
    data_type: real_valued
    input_type: static_input
  - name: DaysWkDrinkAlc
    data_type: real_valued
    input_type: static_input
  - name: DaysMonBingeAlc
    data_type: real_valued
    input_type: static_input
  - name: T1DDiagAge
    data_type: real_valued
    input_type: static_input
  - name: NumHospDKA
    data_type: real_valued
    input_type: static_input
  - name: NumSHSinceT1DDiag
    data_type: real_valued
    input_type: static_input
  - name: InsDeliveryMethod
    data_type: categorical
    input_type: static_input
  - name: UnitsInsTotal
    data_type: real_valued
    input_type: static_input
  - name: NumMeterCheckDay
    data_type: real_valued
    input_type: static_input
  - name: Aspirin
    data_type: real_valued
    input_type: static_input
  - name: Simvastatin
    data_type: real_valued
    input_type: static_input
  - name: Lisinopril
    data_type: real_valued
    input_type: static_input
  - name: "Vitamin D"
    data_type: real_valued
    input_type: static_input
  - name: "Multivitamin preparation"
    data_type: real_valued
    input_type: static_input
  - name: Omeprazole
    data_type: real_valued
    input_type: static_input
  - name: atorvastatin
    data_type: real_valued
    input_type: static_input
  - name: Synthroid
    data_type: real_valued
    input_type: static_input
  - name: "vitamin D3"
    data_type: real_valued
    input_type: static_input
  - name: Hypertension
    data_type: real_valued
    input_type: static_input
  - name: Hyperlipidemia
    data_type: real_valued
    input_type: static_input
  - name: Hypothyroidism
    data_type: real_valued
    input_type: static_input
  - name: Depression
    data_type: real_valued
    input_type: static_input
  - name: "Coronary artery disease"
    data_type: real_valued
    input_type: static_input
  - name: "Diabetic peripheral neuropathy"
    data_type: real_valued
    input_type: static_input
  - name: Dyslipidemia
    data_type: real_valued
    input_type: static_input
  - name: "Chronic kidney disease"
    data_type: real_valued
    input_type: static_input
  - name: Osteoporosis
    data_type: real_valued
    input_type: static_input
  - name: "Proliferative diabetic retinopathy"
    data_type: real_valued
    input_type: static_input
  - name: Hypercholesterolemia
    data_type: real_valued
    input_type: static_input
  - name: "Erectile dysfunction"
    data_type: real_valued
    input_type: static_input
  - name: "Type I diabetes mellitus"
    data_type: real_valued
    input_type: static_input

# Drop
drop: null

# NA values abbreviation
nan_vals: null

# Interpolation parameters
interpolation_params:
  gap_threshold: 45
  min_drop_length: 240

# Splitting parameters
split_params:
  test_percent_subjects: 0.1
  length_segment: 240
  random_state: 0

# Encoding parameters
encoding_params:
  date: 
    - year
    - month
    - day
    - hour
    - minute

# Scaling parameters
scaling_params:
  scaler: None

# Model params
max_length_input: 192
length_pred: 12

linreg:
  in_len: 84

linreg_covariates:
  in_len: 84

tft:
  in_len: 132
  max_samples_per_ts: 200
  hidden_size: 96
  num_attention_heads: 3
  dropout: 0.14019930679548182
  lr: 0.003399303384204884
  batch_size: 48
  max_grad_norm: 0.9962755235072169

tft_covariates:
  in_len: 108
  max_samples_per_ts: 50
  hidden_size: 112
  num_attention_heads: 2
  dropout: 0.1504541564537306
  lr: 0.0018430630797167395
  batch_size: 48
  max_grad_norm: 0.9530046023189843

xgboost:
  in_len: 84
  lr: 0.722
  subsample: 0.9
  min_child_weight: 5.0
  colsample_bytree: 1.0
  max_depth: 10
  gamma: 0.5
  alpha: 0.271
  lambda_: 0.07100000000000001
  n_estimators: 416

xgboost_covariates:
  in_len: 96
  lr: 0.48000000000000004
  subsample: 1.0
  min_child_weight: 2.0
  colsample_bytree: 0.9
  max_depth: 6
  gamma: 1.5
  alpha: 0.159
  lambda_: 0.025
  n_estimators: 320

transformer:
  in_len: 96
  max_samples_per_ts: 50
  d_model: 128
  n_heads: 2
  num_encoder_layers: 2
  num_decoder_layers: 4
  dim_feedforward: 64
  dropout: 0.0017011626095738697
  lr: 0.0007790307889667749
  batch_size: 32
  lr_epochs: 4
  max_grad_norm: 0.4226615744655383

transformer_covariates:
  in_len: 96
  max_samples_per_ts: 50
  d_model: 128
  n_heads: 4
  num_encoder_layers: 1
  num_decoder_layers: 4
  dim_feedforward: 448
  dropout: 0.1901296977134417
  lr: 0.000965351785309486
  batch_size: 48
  lr_epochs: 4
  max_grad_norm: 0.19219462323820113

nhits:
  in_len: 96
  max_samples_per_ts: 200
  kernel_sizes: 4
  dropout: 0.12642017123585755
  lr: 0.00032840023694932384
  batch_size: 64
  lr_epochs: 16

nhits_covariates:
  in_len: 96
  max_samples_per_ts: 50
  kernel_sizes: 3
  dropout: 0.10162895545943862
  lr: 0.0009200129411689094
  batch_size: 32
  lr_epochs: 2

gluformer:
  in_len: 144
  max_samples_per_ts: 100
  d_model: 512
  n_heads: 8
  d_fcn: 1408
  num_enc_layers: 1
  num_dec_layers: 4

latentode:
  in_len: 48
  max_samples_per_ts: 100
  latents: 20
  rec_dims: 40
  rec_layers: 3
  gen_layers: 3
  units: 100
  gru_units: 100